// <auto-generated />
using System;
using Identity.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.API.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20220517064142_Property Chnages")]
    partial class PropertyChnages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Identity.API.Models.appUsers", b =>
                {
                    b.Property<Guid>("usId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("Dob");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("EmailId");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Fname");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Lname");

                    b.Property<string>("Mname")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Mname");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedDate")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Role");

                    b.HasKey("usId")
                        .HasName("PK_usId");

                    b.ToTable("appUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
